const GA_ID='G-B20GWHW0NW';
const STORAGE_KEY='faheem_local_memory_v1';
const ga=document.createElement('script');ga.async=true;ga.src=`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`;document.head.appendChild(ga);
window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}window.gtag=gtag;gtag('js',new Date());gtag('config',GA_ID);
const polish=document.createElement('link');polish.rel='stylesheet';polish.href='styles-polish.css';document.head.appendChild(polish);

const navButtons=document.querySelectorAll('.nav-card,.bottom-nav-btn');
const sections=document.querySelectorAll('.content-section');
const daily=document.getElementById('daily-pulse');
const carb=document.getElementById('carb-search');
const plus=document.getElementById('faheem-plus');
const inputModule=daily?.querySelector('.input-module');
const readingInput=document.getElementById('reading-input');
const chipsBox=inputModule?.querySelector('.context-chips');
const overview=daily?.querySelector('.overview-card');
const contexts=[['fasting','صيام'],['before_meal','قبل الأكل'],['after_meal','بعد الأكل'],['activity','نشاط']];
let selectedContext='before_meal',uiReady=false;
function base(){return{profile:{firstVisitAt:null,lastVisitAt:null,visits:0},ui:{lastTab:'daily-pulse'},readings:[],carb:{basket:[],lastSearch:'',lastMeal:null}}}
function load(){try{const r=JSON.parse(localStorage.getItem(STORAGE_KEY))||{},b=base();return{...b,...r,profile:{...b.profile,...(r.profile||{})},ui:{...b.ui,...(r.ui||{})},carb:{...b.carb,...(r.carb||{})},readings:Array.isArray(r.readings)?r.readings:[]}}catch{return base()}}
let state=load();function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}function track(n,p={}){if(typeof gtag==='function')gtag('event',n,p)}
function sameDay(a,b){const x=new Date(a),y=new Date(b);return x.getFullYear()===y.getFullYear()&&x.getMonth()===y.getMonth()&&x.getDate()===y.getDate()}function today(){const n=Date.now();return state.readings.filter(r=>sameDay(r.timestamp,n))}function lastReading(){return state.readings.at(-1)||null}function avg(a){return a.length?Math.round(a.reduce((s,r)=>s+Number(r.value),0)/a.length):null}function time(ts){return new Date(ts).toLocaleTimeString('ar-SA',{hour:'numeric',minute:'2-digit'})}function dateTime(ts){return new Date(ts).toLocaleString('ar-SA',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}function contextLabel(k){return(contexts.find(c=>c[0]===k)||['','بدون سياق'])[1]}function trend(a){if(a.length<2)return'بانتظار أكثر';const d=a.at(-1).value-a.at(-2).value;return d>=15?'صاعد':d<=-15?'هابط':'مستقر'}
function greeting(list){const h=new Date().getHours();if(!state.readings.length&&state.profile.visits<=1)return['أهلًا بك في فهيم','مو لازم تفهم كل شيء الآن.. ابدأ بقراءة وحدة','فهيم يبدأ معك من أول قراءة، ويجمع الصورة خطوة خطوة'];if(!state.readings.length)return['رجعت لفهيم','خلنا نبدأ من أول قراءة','بمجرد تسجيل القراءة يبدأ فهيم يبني لك فهم أوضح'];if(!list.length)return['رجعت لفهيم','نكمل من آخر قراءة',`آخر تسجيل كان ${dateTime(lastReading().timestamp)}`];return[h<12?'صباح الخير':h<17?'خلنا نراجع منتصف اليوم':h<21?'مساء هادئ':'قبل ما ينتهي اليوم',list.length>1?`عندك ${list.length} قراءة اليوم`:'بداية اليوم واضحة',list.length>1?'كل قراءة جديدة تقرّب فهيم من فهم يومك بشكل أدق':'أضف قراءة ثانية إذا تغيّر الوضع، عشان تبدأ الصورة توضح أكثر']}
function nextStep(list){if(!list.length)return['خطوتك الآن','ابدأ بقراءة واحدة فقط، وبعدها فهيم يبدأ يفهم يومك','اقتراح اليوم: سجّل أول قراءة'];if(list.length===1)return['خطوتك الآن','أضف قراءة ثانية مع سياق واضح، عشان يبدأ الاتجاه يظهر لك','الخطوة التالية: سجّل قراءة عند تغيّر الوضع'];if(list.length<3)return['خطوتك الآن','الصورة بدأت توضح. استمر بقراءة جديدة إذا أكلت أو تغيّر النشاط','كل قراءة إضافية تعطي فهيم فهمًا أفضل'];return['خطوتك الآن','استمر بهدوء. سجّل فقط عند الحاجة أو بعد تغيّر ملحوظ','فهيم يتابع يومك محليًا على هذا الجهاز']}
function node(t,c,x=''){const n=document.createElement(t);n.className=c;n.textContent=x;return n}function card(c,h){const n=document.createElement('article');n.className=`module-card ${c}`;n.innerHTML=h;return n}
function selectContext(k){selectedContext=k;chipsBox?.querySelectorAll('.selectable-chip').forEach(c=>{c.classList.toggle('is-selected',c.dataset.context===k);c.setAttribute('aria-pressed',String(c.dataset.context===k))})}function setStatus(t,k){const chip=overview?.querySelector('.status-chip');if(!chip)return;chip.className=`status-chip is-${k}`;chip.innerHTML=`<span class="is-${k}"></span> ${t}`}
function ensureUI(){if(uiReady||!inputModule||!chipsBox||!readingInput)return;uiReady=true;readingInput.disabled=false;readingInput.type='number';readingInput.inputMode='numeric';readingInput.min='20';readingInput.max='600';readingInput.placeholder='مثال 126';const a=document.createElement('div');a.className='reading-actions';a.innerHTML='<button class="save-reading-btn" type="button">حفظ القراءة</button><p class="inline-status">تُنحفظ قراءاتك داخل جهازك فقط.</p>';chipsBox.after(a);a.after(node('p','helper-copy','اختر السياق ثم احفظ القراءة.'));a.nextElementSibling.after(node('p','last-visit-note',''));chipsBox.querySelectorAll('span').forEach((chip,i)=>{const it=contexts[i];if(!it)return;chip.dataset.context=it[0];chip.classList.add('selectable-chip');chip.tabIndex=0;chip.setAttribute('role','button');chip.onclick=()=>selectContext(it[0])});inputModule.after(card('next-step-card','<div class="next-step-head"><span class="step-badge">الآن</span><h3 class="step-title">خطوتك الآن</h3></div><p class="step-copy"></p><p class="step-meta"></p>'));daily.querySelector('.insight-card').after(card('reading-log-card','<div class="module-title"><div><h3>سجل القراءات</h3><p>آخر ما حفظته على هذا الجهاز.</p></div></div><div class="reading-log-empty">ما فيه قراءات بعد.</div><div class="reading-log-list"></div>'));a.querySelector('button').onclick=saveReading;readingInput.onkeydown=e=>{if(e.key==='Enter')saveReading()}}
function render(){ensureUI();selectContext(selectedContext);const list=today(),last=lastReading(),average=avg(list),tr=trend(list),g=greeting(list),step=nextStep(list);const h=daily.querySelector('.screen-heading');h.querySelector('p').textContent=g[0];h.querySelector('h2').textContent=g[1];overview.querySelector('.overview-head h3').textContent=list.length?'نبض يومك بدأ يتكوّن':'ابدأ أول قراءة';overview.querySelector('.reading-row strong').textContent=last?last.value:'--';overview.querySelector('.overview-note').textContent=g[2];setStatus(!list.length?'جاهز للتسجيل':list.length<3?'الصورة بدأت توضح':'اليوم نشط',!list.length?'ready':list.length<3?'warm':'alert');const st=overview.querySelectorAll('.overview-stats div');[['آخر قراءة',last?last.value:'--'],['الاتجاه',tr],['متوسط اليوم',average||'--']].forEach((x,i)=>{st[i].querySelector('span').textContent=x[0];st[i].querySelector('strong').textContent=x[1]});const m=daily.querySelectorAll('.metric-grid .metric-card');[[last?last.value:'--','mg/dL'],['--','قريبًا'],[tr,list.length?`${list.length} قراءة`:'بداية']].forEach((x,i)=>{m[i].querySelector('strong').textContent=x[0];m[i].querySelector('small').textContent=x[1]});document.querySelector('.helper-copy').textContent=list.length?`اليوم عندك ${list.length} قراءة.`:'ابدأ بقراءة واحدة فقط، وبعدها يبدأ النمط يتكوّن.';document.querySelector('.last-visit-note').textContent=state.profile.lastVisitAt?`آخر زيارة: ${dateTime(state.profile.lastVisitAt)}`:'هذه أول زيارة محفوظة على هذا الجهاز.';document.querySelector('.step-title').textContent=step[0];document.querySelector('.step-copy').textContent=step[1];document.querySelector('.step-meta').textContent=step[2];daily.querySelector('.insight-card p').textContent=list.length?'فهيم يحفظ قراءاتك محليًا على هذا الجهاز فقط، ويساعدك تلاحظ النمط بدون أي قرار علاجي.':'فهيم يساعدك تنظّم وتفهم، لكن أي قرار علاجي يبقى مع الطبيب أو الفريق الصحي.';renderLog();plus.querySelector('.screen-heading p').textContent=state.readings.length>=3?'فهيم بدأ يبني فهمًا أوضح ليومك':'كل ما زادت قراءاتك، صارت إجابات فهيم أذكى'}
function renderLog(){const e=document.querySelector('.reading-log-empty'),b=document.querySelector('.reading-log-list');if(!e||!b)return;b.innerHTML='';if(!state.readings.length){e.hidden=false;b.hidden=true;return}e.hidden=true;b.hidden=false;state.readings.slice(-8).reverse().forEach(r=>{const row=document.createElement('div');row.className=`reading-log-item ${r.context==='after_meal'?'is-warm':r.context==='activity'?'is-calm':''}`;row.innerHTML=`<div class="reading-log-copy"><strong>${r.value}</strong><span>mg/dL</span><p>${contextLabel(r.context)}</p></div><div class="reading-log-meta"><span>${time(r.timestamp)}</span></div>`;b.appendChild(row)})}
function showStatus(msg,type){const s=document.querySelector('.inline-status');s.textContent=msg;s.className=`inline-status ${type?`is-${type}`:''}`}function saveReading(){const v=Number(readingInput.value);if(!readingInput.value||Number.isNaN(v)){showStatus('أدخل قراءة صحيحة أولًا.','error');return}if(v<20||v>600){showStatus('القراءة لازم تكون بين 20 و 600.','error');return}state.readings.push({id:String(Date.now()),value:v,context:selectedContext,timestamp:Date.now()});save();readingInput.value='';showStatus('تم حفظ القراءة على هذا الجهاز.','success');track('reading_added',{context:selectedContext,reading_value:v});render()}
function setupCarbPage(){if(!carb)return;carb.innerHTML=`<div class="screen-heading"><p>إنقاذ سريع وقت الأكل</p><h2 id="carb-title">وش بتاكل؟</h2></div><article class="module-card carb-dream"><div class="module-title"><div><h3>ابحث أو احسب بالجرام</h3><p>جهزنا التجربة لمسارين: منتج جاهز بدون وزن، أو أكل موزون مثل رز 120 جرام.</p></div><span class="round-icon">🍽️</span></div><div class="context-chips"><span>ابحث عن الأكل</span><span>بالجرام</span></div></article><article class="module-card search-module"><label for="food-search">وش الأكل؟</label><div class="search-shell"><input id="food-search" type="search" placeholder="رز، صامولي، موز، سن توب، رز وروبيان" /><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m20 20-4.2-4.2"/></svg></div><div class="context-chips"><span>🍚 رز</span><span>🍞 خبز</span><span>🥛 حليب</span><span>🍌 موز</span><span>🧃 سن توب</span></div></article><article class="food-result-card"><div class="food-visual" aria-hidden="true">🍚</div><div class="food-copy"><span class="eyebrow">نتيجة فهيم</span><h3>أرز أبيض مطبوخ</h3><p>كوب مطبوخ أو أدخل الوزن بالجرام إذا كان موزون.</p></div><div class="food-number"><strong>45</strong><span>جم كارب</span></div></article><article class="confidence-card"><div><h3>لو كتبتي: رز أبيض وروبيان</h3><p>فهيم يعاملها كوجبة مركبة: يعطي تقدير سريع أو يسمح بإدخال الكميات لاحقًا.</p></div><div class="confidence-dots"><span></span><span></span><span></span></div></article><div class="basket-card"><div class="module-title"><h3>وجبتك الآن</h3><a href="#">قريبًا</a></div><div class="basket-row"><span>🍚 أرز أبيض مطبوخ</span><strong>45 جم</strong></div><div class="basket-row muted"><span>🍗 دجاج مشوي</span><strong>0 جم</strong></div><div class="total-strip"><span>إجمالي الكارب</span><strong>45 جم</strong></div></div>`}
function activateSection(id,opt={}){navButtons.forEach(b=>{const a=b.dataset.target===id;b.classList.toggle('is-active',a);b.setAttribute('aria-pressed',String(a))});sections.forEach(s=>{const v=s.id===id;s.classList.toggle('is-visible',v);s.hidden=!v});state.ui.lastTab=id;save();if(!opt.skipTracking)track('section_opened',{section_name:id})}
function init(){const now=Date.now();if(!state.profile.firstVisitAt)state.profile.firstVisitAt=now;state.profile.visits=Number(state.profile.visits||0)+1;state.profile.lastVisitAt=now;save();setupCarbPage();render();navButtons.forEach(b=>b.onclick=()=>activateSection(b.dataset.target));activateSection(state.ui.lastTab||'daily-pulse',{skipTracking:true})}init();
