(() => {
  const root = document.querySelector('.app-shell');
  if (!root) return;
  const KEY='faheem_final_state_v1';
  let page='home', context='قبل الأكل', selected=null;
  const foods=[
    {id:'rice',e:'🍚',n:'رز أبيض مطبوخ',a:['رز','ارز','أرز أبيض','رز ابيض'],m:'weight',g:120,c100:28,k100:130,note:'الأدق إذا كان موزون بالجرام.'},
    {id:'bread',e:'🍞',n:'خبز صمون',a:['خبز','صمون','صامولي'],m:'unit',u:'حبة',c:20,k:108,note:'تختلف القيمة حسب الحجم.'},
    {id:'milk',e:'🥛',n:'حليب قليل الدسم',a:['حليب','كوب حليب'],m:'unit',u:'كوب',c:12,k:95,note:'تختلف القيم حسب نوع الحليب.'},
    {id:'dates',e:'🌴',n:'تمرة',a:['تمر','تمرة'],m:'unit',u:'حبة',c:6,k:23,note:'تختلف حسب الحجم والنوع.'},
    {id:'kabsa',e:'🍛',n:'كبسة دجاج',a:['كبسة','كبسه'],m:'unit',u:'صحن متوسط',c:70,k:520,note:'تقدير حسب كمية الرز.'},
    {id:'apple',e:'🍎',n:'تفاح',a:['تفاح','تفاحة'],m:'unit',u:'حبة متوسطة',c:25,k:95,note:'تقدير عام للحبة المتوسطة.'}
  ];
  function load(){try{return JSON.parse(localStorage.getItem(KEY))||{readings:[],meal:[]}}catch{return{readings:[],meal:[]}}}
  let state=load();
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function today(){const d=new Date();return state.readings.filter(r=>{const x=new Date(r.t);return x.toDateString()===d.toDateString()})}
  function last(){return state.readings.at(-1)||null}
  function avg(a){return a.length?Math.round(a.reduce((s,r)=>s+r.v,0)/a.length):'--'}
  function max(a){return a.length?Math.max(...a.map(r=>r.v)):'--'}
  function trend(a){if(a.length<2)return 'بانتظار';const d=a.at(-1).v-a.at(-2).v;return d>=15?'صاعد':d<=-15?'هابط':'مستقر'}
  function greet(){const h=new Date().getHours();return h<12?'صباح الخير':h<18?'مرحبًا':'مساء الخير'}
  function logo(){return '<img class="faheem-logo-img" src="assets/faheem-logo.svg" alt="فهيم">'}
  function shell(){root.innerHTML=`<div class="splash"><div class="splash-card"><div class="fm-logo-holder fm-logo-splash">${logo()}</div><p>نحن هنا لنفهم سكر الدم والكارب معًا</p><div class="splash-panel"><strong>جاري تجهيز يومك...</strong><div class="progress"><span></span></div><div class="dots"><i></i><i></i><i></i></div></div></div></div><main class="app-main"></main><nav class="bottom-nav"><div class="bottom-nav-shell"><button class="nav-btn active" data-page="home"><span class="nicon">⌂</span><span>الرئيسية</span></button><button class="nav-btn" data-page="carb"><span class="nicon">🧺</span><span>كم كارب؟</span></button><button class="nav-btn" data-page="plus"><span class="nicon">★</span><span>فهيم بلس</span></button></div></nav>`;root.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>go(b.dataset.page));setTimeout(()=>root.querySelector('.splash')?.classList.add('hide'),850)}
  function header(sub){return `<header class="app-head"><button class="head-pill" data-go="plus">🔔</button><div class="brand-mini"><h1 class="fm-logo-header">${logo()}</h1><p>${sub}</p></div></header>`}
  function go(p){page=p;root.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()}
  function home(){const t=today(),l=last(),has=t.length>0;return `${header('نحن هنا لنفهم سكر الدم والكارب معًا')}<section class="home-wrap"><div class="hello"><small>${greet()} 👋</small><strong>${has?'يومك بدأ يتضح':'خلنا نبدأ بهدوء'}</strong></div><article class="hero-home"><div><h2>${has?'فهيم يلخص يومك بدل زحمة الأرقام':'افهم جسمك بسهولة'}</h2><p>${has?`عندك ${t.length} قراءة اليوم. نختصرها لك باتجاه واضح وخطوة تالية.`:'راقب سكر دمك، احسب كاربك، واتخذ قرارات أفضل كل يوم.'}</p><button class="primary-btn" data-go="${has?'plus':'carb'}">${has?'عرض التحليل':'ابدأ رحلتك الآن'}</button></div><div class="hero-ill">🧑‍⚕️<i>💧</i><i>📈</i></div></article><section class="quick-grid"><button class="quick-card" data-go="home"><span class="ico">💚</span><b>نبض يومك</b><span>اقرأ قراءاتك والمؤشرات الصحية</span></button><button class="quick-card active" data-go="carb"><span class="ico">🍲</span><b>كم كارب؟</b><span>احسب الكارب لأي وجبة</span></button><button class="quick-card" data-go="plus"><span class="ico">⭐</span><b>فهيم بلس</b><span>تحليل أعمق وتوصيات ذكية</span></button></section><article class="app-card"><div class="summary-head"><h3>ملخص اليوم</h3><span>اليوم</span></div><div class="daily-grid"><div class="daily-box"><span class="dico">💧</span><strong>${l?l.v:'--'}</strong><span>آخر قراءة</span></div><div class="daily-box"><span class="dico">💚</span><strong>${avg(t)}</strong><span>متوسط</span></div><div class="daily-box"><span class="dico">🍽️</span><strong>${state.meal.reduce((s,i)=>s+i.carbs,0)}</strong><span>كارب</span></div><div class="daily-box"><span class="dico">📈</span><strong>${trend(t)}</strong><span>الاتجاه</span></div></div></article><article class="app-card chart-box"><div class="chart-copy"><h3>اتجاه سكر الدم</h3><p>آخر 24 ساعة</p><button class="ghost-btn" data-go="plus">عرض التحليل</button></div><div class="mini-chart"><svg viewBox="0 0 260 110"><path class="chart-grid" d="M0 25H260M0 60H260M0 95H260"/><path class="chart-area" d="M0 70C35 52 52 84 78 64C108 42 128 78 160 48C188 22 207 63 260 45V110H0Z"/><path class="chart-line" d="M0 70C35 52 52 84 78 64C108 42 128 78 160 48C188 22 207 63 260 45"/></svg></div></article><section class="insight-grid"><article class="insight-card"><b>أفضل وقت للاستقرار</b><span>ابدأ بتسجيل قراءة صباحية واحدة.</span></article><article class="insight-card"><b>بعد الأكل</b><span>سجل قراءة بعد الوجبة حتى يظهر النمط.</span></article></section><article class="app-card next-card"><span class="round">＋</span><div><b>خطوتك التالية</b><span>${has?'أضف قراءة مع سياقها.':'احسب كارب أول وجبة أو سجل قراءة.'}</span></div></article></section>`}
  function foodCalc(f){if(!f)return{carbs:0,cal:0,unit:''};if(f.m==='weight'){const g=Number(document.querySelector('.food-grams')?.value||f.g||100);return{carbs:Math.round(f.c100*g/100),cal:Math.round(f.k100*g/100),unit:g+' غرام'}}return{carbs:f.c,cal:f.k,unit:f.u}}
  function searchFoods(q){q=(q||'').trim().toLowerCase();if(!q)return[];return foods.filter(f=>[f.n,...f.a].some(x=>x.toLowerCase().includes(q)||q.includes(x.toLowerCase())))}
  function carb(){return `${header('اعرف كارب أكلك بسرعة')}<div class="page-title"><h2>كم كارب؟</h2><p>ابحث عن أكلك بسرعة</p></div><section class="screen-stack"><div class="search-line"><span>🔎</span><input class="food-q" placeholder="ابحث عن أكلة أو مشروب..."></div><div class="food-hero">🍚 🍎 🥛 🍞</div><div class="mode-tabs"><button class="mode-tab active">بحث مباشر</button><button class="mode-tab">بالوزن</button></div><div class="chips"><button class="chip" data-food="رز">رز أبيض</button><button class="chip" data-food="حليب">حليب</button><button class="chip" data-food="خبز">خبز</button><button class="chip" data-food="تمر">تمر</button></div><article class="app-card"><div class="summary-head"><h3>نتائج فهيم</h3><span>اختر صنف</span></div><div class="food-results"><p class="unit">اكتب اسم الأكل أو اختر من الاختصارات.</p></div></article><article class="app-card answer-card"></article><article class="app-card"><div class="summary-head"><h3>سلة الوجبة</h3><span>${state.meal.length} عناصر</span></div><div class="meal-list">${mealRows()}</div><div class="result-grid"><div class="result-box primary"><span>إجمالي الكارب</span><strong>${state.meal.reduce((s,i)=>s+i.carbs,0)} غ</strong></div><div class="result-box"><span>السعرات</span><strong>${state.meal.reduce((s,i)=>s+i.cal,0)}</strong></div></div></article></section>`}
  function mealRows(){return state.meal.length?state.meal.map((i,n)=>`<div class="meal-item"><span>${i.e}</span><span><b>${i.n}</b><small>${i.unit} · ${i.carbs}غ كارب · ${i.cal} سعرة</small></span><button data-remove="${n}">×</button></div>`).join(''):'<p class="unit">أضف أول صنف للوجبة.</p>'}
  function plus(){const t=today();return `${header('تحليل أعمق ليومك ✨')}<div class="page-title"><h2>فهيم بلس</h2><p>الصورة الكاملة</p></div><section class="screen-stack"><article class="app-card plus-hero"><div class="bot">🤖</div><h2>مساعدك الذكي يحلل بياناتك</h2><p>فهيم بلس يحول القراءات والوجبات إلى ملخص بصري ونصائح قابلة للتطبيق.</p><button class="primary-btn" data-go="home">ابدأ من الرئيسية</button></article><article class="app-card"><div class="summary-head"><h3>الملخص العام</h3><span>يتكوّن الآن</span></div><div class="daily-grid"><div class="daily-box"><span class="dico">🎯</span><strong>${t.length?'82%':'--'}</strong><span>في النطاق</span></div><div class="daily-box"><span class="dico">📋</span><strong>${t.length}</strong><span>قراءات</span></div><div class="daily-box"><span class="dico">📈</span><strong>${trend(t)}</strong><span>الاتجاه</span></div><div class="daily-box"><span class="dico">🍽️</span><strong>${state.meal.length}</strong><span>وجبات</span></div></div></article><article class="app-card"><div class="summary-head"><h3>ما الذي سيقدمه؟</h3><span>قريبًا</span></div><div class="plus-features"><div class="plus-row"><span class="pico">◎</span><div><b>بطاقة تحليل اليوم</b><span>ملخص واضح بدل زحمة القراءات.</span></div></div><div class="plus-row"><span class="pico">⌁</span><div><b>اكتشاف النمط</b><span>الصيام، بعد الأكل، النشاط، والاتجاه.</span></div></div><div class="plus-row"><span class="pico">✦</span><div><b>تقرير أسبوعي</b><span>هدية قابلة للحفظ والمشاركة.</span></div></div></div></article></section>`}
  function render(){const main=root.querySelector('.app-main');main.innerHTML=page==='carb'?carb():page==='plus'?plus():home();bind()}
  function bind(){root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));root.querySelectorAll('.food-q').forEach(inp=>inp.oninput=()=>showFoods(inp.value));root.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>{const i=root.querySelector('.food-q');i.value=b.dataset.food;showFoods(i.value)});root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.meal.splice(+b.dataset.remove,1);save();render()})}
  function showFoods(q){const box=root.querySelector('.food-results');if(!box)return;const arr=searchFoods(q);box.innerHTML=arr.length?arr.map(f=>{const c=foodCalc(f);return `<button class="food-hit" data-id="${f.id}"><span class="emoji">${f.e}</span><span><strong>${f.n}</strong><small>${f.m==='weight'?(f.g+' غرام'):f.u}</small></span><span class="num">${c.carbs}<small>غ</small></span></button>`}).join(''):'<p class="unit">ما لقينا نتيجة واضحة. جرّب كلمة أبسط.</p>';box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{selected=foods.find(f=>f.id===b.dataset.id);showAnswer()})}
  function showAnswer(){const box=root.querySelector('.answer-card');if(!box||!selected)return;const c=foodCalc(selected);box.classList.add('show');box.innerHTML=`<div class="answer-top"><span class="emoji">${selected.e}</span><div><h3>${selected.n}</h3><p>${selected.note}</p></div></div><div class="result-grid"><div class="result-box primary"><span>الكارب</span><strong>${c.carbs} غ</strong></div><div class="result-box"><span>السعرات</span><strong>${c.cal}</strong></div></div>${selected.m==='weight'?`<div class="result-grid"><div class="result-box"><span>الوزن</span><input class="food-grams" type="number" value="${selected.g}"></div><div class="result-box"><span>الوحدة</span><strong>غرام</strong></div></div>`:''}<button class="primary-btn add-meal" style="width:100%;margin-top:12px">أضف إلى الوجبة</button>`;const g=box.querySelector('.food-grams');if(g)g.oninput=showAnswer;box.querySelector('.add-meal').onclick=()=>{const x=foodCalc(selected);state.meal.push({e:selected.e,n:selected.n,carbs:x.carbs,cal:x.cal,unit:x.unit});save();render()}}
  shell();render();
})();
